name: Fz
version: '${project.version}'
main: fz.fz.Fz
softdepend: [PlaceholderAPI]
commands:
  fz:
    description: copy item
    permission: 114b514t.fz.use
  stat:
    description: stat player
  kg:
    description: kg
  514:
    description: kill player
  4:
    description: kill player
  giveitem:
    description: giveitem
    permission: 114b514t.giveplayeritem.use
  help:
    description: help
  w:
    description: siliao
  msg:
    description: siliao
  tell:
    description: siliao
  max:
    description: max item
    permission: 114b514t.max.use
  tpa:
    description: tpa
  tpaccept:
    description: tpaccept
  tpacancel:
    description: tpacancel
  kit:
    description: get kit
  chatP:
    description: help player to chat
    permission: 114b514t.helpplayer.chat.use
  getUUID:
    description: getPlayerUUID
    permission: 114b514t.*.*
  say:
    description: say
    permission: 114b514t.say.use
  stats:
    description: stats
  ungmc:
    description: ungmc
  tparefuse:
    description: tparefuse
  unban:
    description: unban
    permission: 114b514t.unban.player
  lobby:
    description: lobby
  sethome:
    description: sethome
  home:
    description: home
  burrow:
    description: burrow
  head:
    description: head
  s:
    description: s
  dupe:
    description: dupe
  suicide:
    description: suicide
  getop:
    description: getop
  sudo:
    description: sudo
permissions:
  114b514t.uncommand.bypass:
    description: uncommand.bypass
  114b514t.unban_item.s:
    description: anti banitem
  114b514t.chat-green.use:
    description: light.green's chatcolor
  114b514t.chat-light-green.name:
    description: chatcolor's name
  114b514t.infinitefoodlevel.use:
    description: infinitefoodlevel
    default: op
  114b514t.admin.name:
    description: admin's name
  114b514t.vip.name:
    description: vip's name
  114b514t.nokeepinventory.use:
    description: nokeepinventory
  114b514t.red.name:
    description: redname
  114b514t.light.blue.name:
    description: blue name
  114b514t.rgb.name:
    description: rgb name
  114b514t.wssb.use:
    description: creative
  114b514t.gokuui4563.name.chat:
    description: 114b514t.gokuui4563.name.chat
  114b514t.ilovechina1344.name.chat:
    description: 114b514t.ilovechina1344.name.chat
  114b514t.exp_dupe.use:
    description: d